import org.apache.hadoop.ipc.proto.GenericRefreshProtocolProtos.GenericRefreshResponseCollectionProtoOrBuilder;
public class FunctionUse16029 {
public void funcUse() {
GenericRefreshResponseCollectionProtoOrBuilder genericrefreshresponsecollectionprotoorbuilder = new GenericRefreshResponseCollectionProtoOrBuilder();
genericrefreshresponsecollectionprotoorbuilder.getResponses(null);
}
}