import org.apache.hadoop.security.protocolPB.RefreshUserMappingsProtocolServerSideTranslatorPB;
public class FunctionUse4545 {
public void funcUse() {
RefreshUserMappingsProtocolServerSideTranslatorPB refreshusermappingsprotocolserversidetranslatorpb = new RefreshUserMappingsProtocolServerSideTranslatorPB();
refreshusermappingsprotocolserversidetranslatorpb.refreshUserToGroupsMappings(null,null);
}
}